config/routes.rb
Rails.application.routes.draw do

  resources :questions, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :answers, only: [:index, :create]
  end

  root "questions#index"

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question

  validates :description, presence: true
  validates :description, length: { minimum: 50 }

end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers, dependent: :destroy

  validates :title, presence: true
  validates :description, presence: true
  validates :title, length: { minimum: 40 }
  validates :description, length: { minimum: 150 }

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def index

    @question = Question.find(params[:question_id])
    @answers = @question.answers

  end

  def create
    @question = Question.find(params[:question_id])
    @answer = Answer.new(answer_params, question_id: @question.id)
    @answer.question = @question

    if @answer.save
      redirect_to question_path(@question)
    else
      flash[:notice] = "Your answer is weak."
      redirect_to question_path(@question)
    end
  end



  private

  def answer_params
    params.require(:answer).permit(:description)
  end
end

app/controllers/questions_controller.rb
require 'pry'

class QuestionsController < ApplicationController
  def index
    @questions = []
    @questions_all = Question.all
    @questions_all.each do |q|
      @questions.unshift q
    end
  end

  def show
    @question = Question.find(params[:id])
    @answers = Answer.where(question_id: @question.id)
    @answer = Answer.new
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to question_path(@question)
    else
      flash[:notice] = "Your question is weak."
      render action: 'new'
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    if @question.update_attributes(question_params)
      redirect_to question_path(@question)
    else
      render 'edit'
    end
  end

  def destroy
    question = Question.find(params[:id])

    question.destroy

    redirect_to questions_path
  end


  private

  def question_params
    params.require(:question).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RescueMission</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/questions/edit.html.erb
<%= form_for(@question) do |f| %>

  <div class="field">
    <%= f.label :description, "Edit Question Below." %><br />
    <%= f.text_area :description, size: "50x15" %>
  </div>

  <div class="actions">
    <%= f.submit "Update Question" %>
  </div>
<% end %>

</br>

<%= form_tag(question_path(@question), method: :delete) do %>
  <div class="actions">
    <%= submit_tag 'Delete Question' %>
  </div>
<% end %>

</br>

<%= link_to "back to question", question_path(@question) %>

app/views/questions/index.html.erb
<h1>Questions</h1>
<br>

<h4>Questions Listed Below...</h4>

<ul>
  <% @questions.each do |q| %>
  <li>
    <%= link_to q.title, question_path(q)%>
  </li>
  </br>
  <% end %>
</ul>


<%= link_to "Submit new question", new_question_path%>

app/views/questions/new.html.erb
<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
<% end %>

<%= form_for(@question) do |f| %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description, "Submit Question Below." %><br />
    <%= f.text_area :description, size: "50x15" %>
  </div>

  <div class="actions">
    <%= f.submit "Submit Question" %>
  </div>
<% end %>


<%= link_to "back to questions list", questions_path %>

app/views/questions/show.html.erb
<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
<% end %>

<h1>Question and Answers</h1>


<div style="padding-left: 4em ">

<h2><%= @question.title %></h2>

  <div class="definelength" >
    <p> <%= @question.description %> </p>
  </div>

  <%= form_tag(edit_question_path(@question), method: :get) do %>
    <div class="actions">
      <%= submit_tag 'Edit Question' %>
    </div>
  <% end %>

  <%= form_tag(question_path(@question), method: :delete) do %>
    <div class="actions">
      <%= submit_tag 'Delete Question' %>
    </div>
  <% end %>

</div>

<h3>Answers:</h3>

<div class="definelength">
  <ol>
    <% @answers.each do |answer| %>
    <li><%= answer.description %></li>
  </br>
    <% end %>
  </ol>
</div>


<%= form_for [@question, @answer] do |f| %>
  <div class="field">
    <%= f.label :description, "Submit Answer Below." %><br />
    <%= f.text_area :description, size: "50x15" %>
  </div>

  <div class="actions">
    <%= f.submit "Submit Answer" %>
  </div>
<% end %>

</br>

<%= link_to "back to questions list", questions_path %>